from odoo import api, fields, models, _
from odoo.exceptions import AccessError, UserError


class ProfitShareLine(models.Model):
    _name = "profit.share.line"
    _description = "Profit Sharing Line"
    _order = "computation_id desc, share_type_id, recipient_id, id"

    computation_id = fields.Many2one(
        "profit.share.computation",
        required=True,
        ondelete="cascade",
        index=True,
    )
    rule_id = fields.Many2one(
        "profit.share.rule",
        required=True,
        ondelete="restrict",
        index=True,
    )
    rule_name = fields.Char(
        string="Rule Name Snapshot",
        readonly=True,
        help="Rule name captured when the computation was generated, so historical output remains readable even if the rule is renamed later.",
    )
    share_type_id = fields.Many2one(
        "profit.share.type",
        required=True,
        ondelete="restrict",
        index=True,
    )
    share_type_name = fields.Char(
        string="Share Type Snapshot",
        readonly=True,
        help="Share Type name captured when the computation was generated.",
    )
    recipient_id = fields.Many2one(
        "res.partner",
        required=True,
        ondelete="restrict",
        index=True,
    )
    recipient_name = fields.Char(
        string="Recipient Name Snapshot",
        readonly=True,
        help="Recipient name captured when the computation was generated.",
    )
    company_id = fields.Many2one("res.company", required=True, index=True)
    currency_id = fields.Many2one("res.currency", required=True)
    computation_state = fields.Selection(
        related="computation_id.state",
        string="Batch State",
        readonly=True,
    )
    approval_required = fields.Boolean(
        related="computation_id.approval_required",
        string="Approval Required",
        readonly=True,
    )
    source_type = fields.Selection(
        [("pos_revenue", "POS Revenue"), ("net_profit", "Net Profit")],
        required=True,
        index=True,
    )
    base_amount = fields.Monetary(required=True, currency_field="currency_id")
    computation_type = fields.Selection(
        [("percentage", "Percentage"), ("flat", "Flat Amount")],
        required=True,
    )
    rate_applied = fields.Float(
        digits=(16, 4),
        help="Snapshot of the applied rate. Percentage for percentage rules; flat amount for flat rules.",
    )
    percentage_applied = fields.Float(digits=(16, 4))
    flat_amount_applied = fields.Monetary(currency_field="currency_id")
    share_amount = fields.Monetary(required=True, currency_field="currency_id", index=True)
    payment_state = fields.Selection(
        [("unpaid", "Unpaid"), ("paid", "Paid")],
        required=True,
        default="unpaid",
        index=True,
    )
    payment_move_id = fields.Many2one(
        "account.payment",
        string="Payment",
        ondelete="set null",
        check_company=True,
        help="Optional link when the payment is recorded in Odoo Accounting.",
    )
    effective_date_from = fields.Date(required=True)
    effective_date_to = fields.Date(required=True)
    priority_applied = fields.Integer()

    _sql_constraints = [
        (
            "profit_share_line_batch_rule_uniq",
            "unique(computation_id, rule_id)",
            "A sharing rule can only produce one line in the same computation batch.",
        ),
    ]

    @api.model_create_multi
    def create(self, vals_list):
        if not self.env.su:
            raise AccessError(_("Share lines are generated by the computation engine and cannot be created manually."))
        return super().create(vals_list)

    def _validate_payment_transition(self, target_state):
        for line in self:
            batch = line.computation_id
            if target_state == "paid":
                ready_state = "approved" if batch.approval_required else "confirmed"
                if batch.state not in (ready_state, "paid"):
                    raise UserError(
                        _(
                            "Share line %(line)s cannot be marked Paid because batch %(batch)s is in %(state)s state."
                        )
                        % {
                            "line": line.display_name,
                            "batch": batch.display_name,
                            "state": batch.state.title(),
                        }
                    )
            elif target_state == "unpaid" and batch.state not in ("confirmed", "approved", "paid"):
                raise UserError(
                    _(
                        "Share line %(line)s cannot be reopened because batch %(batch)s is in %(state)s state."
                    )
                    % {
                        "line": line.display_name,
                        "batch": batch.display_name,
                        "state": batch.state.title(),
                    }
                )

    def write(self, vals):
        payment_fields = {"payment_state", "payment_move_id"}
        protected_snapshot_fields = {
            "rule_id",
            "rule_name",
            "share_type_id",
            "share_type_name",
            "recipient_id",
            "recipient_name",
            "company_id",
            "currency_id",
            "source_type",
            "base_amount",
            "computation_type",
            "rate_applied",
            "percentage_applied",
            "flat_amount_applied",
            "share_amount",
            "effective_date_from",
            "effective_date_to",
            "priority_applied",
        }

        if protected_snapshot_fields.intersection(vals) and not self.env.su:
            raise AccessError(_("Computation snapshot fields are generated by the engine and cannot be edited manually."))

        if payment_fields.intersection(vals) and not self.env.su:
            if not self.env.user.has_group("profit_sharing.group_profit_share_payment"):
                raise AccessError(_("You are not allowed to update profit-sharing payment information."))
            if "payment_state" in vals:
                raise AccessError(_("Change payment status using the Mark Paid / Reopen actions."))
            for line in self:
                ready_state = "approved" if line.computation_id.approval_required else "confirmed"
                if line.computation_id.state not in (ready_state, "paid"):
                    raise UserError(
                        _("Payment references can only be edited when the batch is ready for payment (%s) or already Paid.")
                        % ready_state.title()
                    )

        result = super().write(vals)
        if "payment_state" in vals and not self.env.context.get("profit_share_skip_batch_sync"):
            self.mapped("computation_id")._sync_paid_state_from_lines()
        return result

    def unlink(self):
        if not self.env.su:
            raise AccessError(_("Share lines cannot be deleted manually. Recompute or delete the Draft computation batch instead."))
        return super().unlink()

    def action_mark_paid(self):
        if not self.env.su and not self.env.user.has_group("profit_sharing.group_profit_share_payment"):
            raise AccessError(_("You are not allowed to mark profit-sharing lines as paid."))
        self._validate_payment_transition("paid")
        actor_id = self.env.user.id
        self.with_context(profit_share_payment_actor_id=actor_id).sudo().write({"payment_state": "paid"})
        return True

    def action_mark_unpaid(self):
        if not self.env.su and not self.env.user.has_group("profit_sharing.group_profit_share_payment"):
            raise AccessError(_("You are not allowed to reopen profit-sharing payment status."))
        self._validate_payment_transition("unpaid")
        self.sudo().write({"payment_state": "unpaid", "payment_move_id": False})
        return True
